image: gitpod/workspace-full

tasks:
  - name: terraform
    before:
      ./bin/terraform-cli-install

  - name: tools
    before:
      sudo apt-get update
      sudo apt-get install -y tree

  - name: aws-cli
    before:
      ./bin/aws-cli-install

  - name: kubectl
    before:
      ./bin/kubectl
      
  - name: helm
    before:
      ./bin/helm-install

  - name: tree
    command: sudo apt-get install tree

  - name: clear
    command: clear
